export enum TEAM_MEMBER {
  ADD_TEAM_MEMBER = 'TEAM_MEMBER_ADD_TEAM_MEMBER',
  UPDATE_TEAM_MEMBER = 'TEAM_MEMBER_UPDATE_TEAM_MEMBER',
  DELETE_TEAM_MEMBER = 'TEAM_MEMBER_DELETE_TEAM_MEMBER',
  VIEW_TEAM_DIRECTORY = 'TEAM_MEMBER_VIEW_TEAM_DIRECTORY',
}
