name: DEV Lambda Deployment

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: "AWS Region"
        required: true
        default: "us-east-1"
      REGION_PREFIX:
        description: "Region Prefix"
        required: true
        default: "use1"
      FUNCTION_DIR:
        description: "Function Directory"
        required: true
        default: "function"
      ENV:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  deployment-pipeline:
    uses: jayvaru2025/common-pipeline/.github/workflows/lambda.yml@main
    with:
      AWS_REGION: ${{ github.event.inputs.AWS_REGION }}
      REGION_PREFIX: ${{ github.event.inputs.REGION_PREFIX }}
      FUNCTION_DIR: ${{ github.event.inputs.FUNCTION_DIR }}
      ENV: ${{ github.event.inputs.ENV }}
      LAMBDA_FUNCTION_NAME: ch-lmda-backend-use1-dev
    secrets:
      REPO_ACCESS_TOKEN_: ${{ secrets.REPO_ACCESS_TOKEN_ }}